Add desktop file, custom launch script and an installer for them
yazgoo/umberwm pull request #18
Opened 2021-05-12 01:39 UTC by mfdorst

In order to launch umberwm from a display manager (such as gdm) you need a `.desktop` file in `/usr/share/xsessions`. This provides that file.

It also provides a launcher script `umberwm-start` which allows the user to run custom scripts on launch (personally I have to do a few `xrandr` and `amixer` commands in order to use the correct display and sound outputs. Currently the script just calls `umberwm`, but it being there makes the launch behavior easy to customize.

It also provides an installer script which will do three things:
1. Symlink the `umberwm` binary to `/usr/bin`
2. Symlink `umberwm-start` to `/usr/bin`
3. Copy `umberwm.desktop` to `/usr/share/xsessions` (it cannot be a symlink)

2021-05-12 01:52 UTC, mfdorst commented
Oh I made a dumb mistake. I moved `main.rs` into this repo, since I don't see any point in it being separate. My installer script therefore assumes that the binary will be in `umberwm/target/release`, but obviously that is not the case. Oops.

2021-05-16 00:40 UTC, mfdorst commented
Since it looks like we are adding `main.rs` to this repo as per #19, this can be reopened.

2021-05-16 00:41 UTC, mfdorst commented
I suppose `umberwm-start` should be modified to reflect #25.

2021-05-16 06:19 UTC, yazgoo commented
Agreed.
Also, could you please mention install script in README.md ?

2021-05-16 06:38 UTC, mfdorst commented
Sure thing

2021-05-16 07:10 UTC, mfdorst commented
I added the auto-restart code to `umberwm-start`, so that is preconfigured to work.

2021-05-16 11:17 UTC, yazgoo requested changes

2021-05-16 11:17 UTC, yazgoo commented on README.md
> +5. Run `cargo build --release`. The binary will be available in `target/release/umerwm`.
```suggestion
5. Run `cargo build --release`. The binary will be available in `target/release/umberwm`.
```

2021-05-16 11:17 UTC, yazgoo commented on README.md
> +6. Run `./install.py`. This will do three things:
```suggestion
6. Optionally, run `./install.py`. This will do three things:
```

2021-05-16 22:09 UTC, mfdorst commented on README.md
> +5. Run `cargo build --release`. The binary will be available in `target/release/umerwm`.
Oops lol

2021-05-16 22:09 UTC, mfdorst commented on README.md
> +6. Run `./install.py`. This will do three things:
Good change, will do

2021-05-17 04:59 UTC, merged